implementing bvh;

public static const float M_PI = 3.14159265358979323846;   // pi
public static const float M_PI_2 = 1.57079632679489661923; // pi/2
public static const float FLT_MAX = 3.402823466e+38F;      // max float value
public static const float FLT_EPSILON = 1.192092896e-07F;  // smallest float value such that 1.0+FLT_EPSILON != 1.0
public static const uint UINT_MAX = 4294967295;            // max unsigned int value